# Generated by Django 2.2 on 2020-01-09 19:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'badger'), (2, 'monkey'), (3, 'bear')], default=1)),
                ('age', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male')], default=1)),
                ('age', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp38.Animal')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp38.Visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lim_age', models.PositiveIntegerField(default=16, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(150)])),
                ('lim_date', models.DateTimeField(default=django.utils.timezone.now, max_length=datetime.datetime(2020, 1, 10, 19, 6, 17, 125986, tzinfo=utc))),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp38.Visitor')),
            ],
        ),
    ]
