# Generated by Django 2.2 on 2020-01-09 19:28

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp38', '0002_auto_20200109_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='lim_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=datetime.datetime(2020, 1, 10, 19, 28, 29, 29538, tzinfo=utc)),
        ),
    ]
